version: '3.4'

services:

    jira-software:
        container_name: jira
        image: atlassian/jira-software
        ports:
            - "8080:8080"
        volumes:
            - type: volume
              source: jira-software-data
              target: /var/atlassian/application-data/jira
        environment:
            ATL_JDBC_URL: jdbc:postgres://postgres:5432/test
            ATL_JDBC_USER: user
            ATL_JDBC_PASSWORD: password
            ATL_DB_DRIVER: org.postgresql.Driver
            ATL_DB_TYPE: postgres95
            ATL_DB_SCHEMA_NAME: public


volumes:
    jira-software-data:
