version: '3.4'

services:

    jira-software:
      container_name: jira
      image: chrisperkins/jira-software:7.13.5-ubuntu
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
      ports:
        - "9090:8080"
        - "5005:5005"
      volumes:
        - type: volume
          source: jira-software-data
          target: /var/atlassian/application-data/jira
      networks:
        - jira_net
    #   environment:
    #     ATL_JDBC_URL: jdbc:postgres://postgres:5432/test
    #     ATL_JDBC_USER: user
    #     ATL_JDBC_PASSWORD: password
    #     ATL_DB_DRIVER: org.postgresql.Driver
    #     ATL_DB_TYPE: postgres96
    #     ATL_DB_SCHEMA_NAME: public

    postgres:
      image: chrisperkins/postgres:9.6.3
      container_name: postgres_jira
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: any
          max_attempts: 3
      ports:
        - "5432"
      volumes:
        - type: volume
          source: postgres_data
          target: /var/lib/postgresql/data
      environment:
        - DB_PASS=admin
        - DB_NAME=jira
        - DB_USER=admin
      networks:
        - jira_net

networks:
  jira_net:
    driver: overlay

volumes:
    jira-software-data:
    postgres_data:
