version: '3.4'
services:
  jirapostgres:
    build:
      context: ./postgres-build
      dockerfile: ./Dockerfile
    container_name: postgres_4_jira
    ports:
      - "65432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      - DB_PASS=admin
      - DB_NAME=jira
      - DB_USER=admin
    networks:
      - jira_net
 
networks:
  jira_net:
    driver: bridge

volumes:
  postgres_data: